# Generated by Django 5.1.4 on 2025-01-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='Employee', max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
