# Generated by Django 5.1.4 on 2025-01-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hashed', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
